{ msgid: 6,
  stickers: 
   [ { category: 'laptop_sticker',
       name: 'reddit',
       price: 0,
       state: 'active',
       path: 'reddit',
       _id: '4f873b32af173a2903816e52',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Twitter',
       price: 0,
       state: 'active',
       path: 'twitter',
       _id: '4f86febfe77989117e00000a',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Codecademy',
       price: 0,
       state: 'active',
       path: 'codecademy',
       _id: '4f86fd27e77989117e000000',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Facebook',
       price: 0,
       state: 'active',
       path: 'facebook',
       _id: '4f86fd3ee77989117e000002',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Stack Overflow',
       price: 0,
       state: 'active',
       path: 'stackoverflow',
       _id: '4f86fe5de77989117e000007',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Etsy',
       price: 0,
       state: 'active',
       path: 'etsy',
       _id: '4f86fd32e77989117e000001',
       description: '' },
     { category: 'laptop_sticker',
       name: 'GitHub',
       price: 0,
       state: 'active',
       path: 'github',
       _id: '4f86fe06e77989117e000004',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Pinterest',
       price: 0,
       state: 'active',
       path: 'pinterest',
       _id: '4f86fe33e77989117e000006',
       description: '' },
     { category: 'laptop_sticker',
       name: 'turntable',
       price: 0,
       state: 'active',
       path: 'turntable',
       _id: '4f86fea8e77989117e000009',
       description: '' },
     { category: 'laptop_sticker',
       name: 'stickybits',
       price: 0,
       state: 'active',
       path: 'stickybits',
       _id: '4f86fe84e77989117e000008',
       description: '' },
     { category: 'laptop_sticker',
       name: 'Meetup',
       price: 0,
       state: 'active',
       path: 'meetup',
       _id: '4f86fe15e77989117e000005',
       description: '' },
     { category: 'laptop_sticker',
       name: 'foursquare',
       price: 0,
       state: 'active',
       path: 'foursquare',
       _id: '4f86fdede77989117e000003',
       description: '' } ],
  success: true }